# Simple workflow for deploying static content to GitHub Pages
name: topbook

on:
  schedule:
    - cron: "0 4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Dependences
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python baidu.py
      - name: Commit
        run: |
          git config --global user.email  118094961+makcol@users.noreply.github.com
          git config --global user.name makcol
          git add .
          git commit -m "action:`date`"
          git pull --rebase
